### ISSUE TITLE
Research on Maven Reactor and Deploying all submodules on CI

### ISSUE THREAD

**Issue by mekya** [ant-media/Ant-Media-Server#114]

**Comment by mekya** [comment]
Ant Media Server consists of sub projects which are mainly
https://github.com/ant-media/ant-media-server-parent
https://github.com/ant-media/Ant-Media-Server
https://github.com/ant-media/Ant-Media-Server-Common
https://github.com/ant-media/Ant-Media-Server-Service
https://github.com/ant-media/red5-plugins/tree/master/tomcat
https://github.com/ant-media/WebRTCApp
https://gitlab.com/Ant-Media/SampleApp
https://gitlab.com/Ant-Media/ManagementConsole_AngularApp


Enterprise Edition has these projects as well
https://gitlab.com/Ant-Media/Ant-Media-Enterprise
https://gitlab.com/Ant-Media/WebRTCApp4Enterprise

What we want is finding a simple way to build all these projects and make deployments to maven repos automatically. Keep in mind that https://gitlab.com/Ant-Media/Ant-Media-Enterprise will not be deployed to Maven.  All the other subprojects may be deployed automatically when it is pushed to repo. 

Btw, parent pom(https://github.com/ant-media/ant-media-server-parent) contains all version information of submodules.

**Comment by maydin** [comment]
@mekya when will these projects will be deployed to maven? If you trigger deploy automatically when they are pushed to repo, how will you define the version number?

**Comment by mekya** [comment]
Yeah trigger deploy automatically, version number is being fetched from parent pom

**Comment by maydin** [comment]
@mekya could you please send me the central maven repo url that is used with username and password.

**Comment by mekya** [comment]
I am sending username and password to your e-mail. 


Community Edition is deployed in these lines. It is deployed to mvn for all commits(including snapshots)
It is deployed to github if it is in master branch and it is tagged. 
```
deploy:
  - provider: script
    script: "mvn deploy -P assemble -DskipTests --quiet --settings mvn-settings.xml"
    skip_cleanup: true
    on:
      tags: false
      all_branches: true
  - provider: releases
    api_key: $GITHUB_OAUTH_TOKEN
    file_glob: true
    file: "target/ant-media-server-community*.zip"
    skip_cleanup: true
    name: "Ant Media Server Community $(date +'%F-%T')"
    prerelease: true
    on:
      tags: true
      branch: master
```

When packaging the server below project should be deployed in advance
* [Parent]( https://github.com/ant-media/ant-media-server-parent) 
* [Ant-Media-Server](https://github.com/ant-media/Ant-Media-Server)
* [Ant-Media-Server-Common](https://github.com/ant-media/Ant-Media-Server-Common)
* [Ant-Media-Server-Service](https://github.com/ant-media/Ant-Media-Server-Service)
* [Tomcat Plugin](https://github.com/ant-media/red5-plugins/tree/master/tomcat)
* [WebRTCApp](https://github.com/ant-media/WebRTCApp)
* [LiveApp](https://gitlab.com/Ant-Media/SampleApp)
* [ConsoleApp](https://gitlab.com/Ant-Media/ManagementConsole_AngularApp)

Our mission is provide required improvements or arrangements to deploy all these things with one command
