### ISSUE TITLE
[Flutter SDK] C++ addTrack failed

### ISSUE THREAD

**Issue by mustafaboleken** [ant-media/Ant-Media-Server#6376]
When using the multitrack conference, Flutter SDK throws the C++ addTrack failed error on Android devices.

Steps to reproduce:

- Join into room1 on Web client as participant1 
- Join into room1 on Web client as participant2
- Join into room1 on Android client with Flutter SDK as participant3
- You will see `C++ addTrack failed` error in the logs, even everything works fine

**Comment by arlakay** [comment]
same issue

**Comment by mustafaboleken** [comment]
Hi @arlakay 

Can you please test the open pr and let us know if it works for you or not. https://github.com/ant-media/WebRTC-Flutter-SDK/pull/50

```
dependencies:   
     ant_media_flutter:
       git:
         url: https://github.com/ant-media/WebRTC-Flutter-SDK.git
         ref: fixConferenceCrashIssue
```
